management:
  endpoints:
    web:
      exposure:
        include: env,info,health,loggers
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true

spring:
  application:
    name: customer-job-engine
  batch:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:customer-engine-db
    job:
      enabled: false

---
spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8083
